MVC_Vaje202122_Priprava/Models/ErrorViewModel.cs
using System;

namespace MVC_Vaje202122_Priprava.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC_Vaje202122_Priprava/Models/Kategorija.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Vaje202122_Priprava.Models
{
    public class Kategorija
    {

        [Key]
        public int Id { get; set; }

        [Required]
        public string naziv { get; set; }

       
        [Display (Name ="Vrstni red")]
        [Range(1,100,ErrorMessage ="Vrstni red mora imeti vrednost med 1 in 100!!")]
        public int vrstniRed { get; set; }


        public DateTime ustvarjeno { get; set; } = DateTime.Now;

        public string opis { get; set; }

        public string url { get; set; }

    }
}

MVC_Vaje202122_Priprava/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVC_Vaje202122_Priprava.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Vaje202122_Priprava.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC_Vaje202122_Priprava/Controllers/KategorijaController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Vaje202122_Priprava.Data;
using MVC_Vaje202122_Priprava.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Vaje202122_Priprava.Controllers
{

    public class KategorijaController : Controller
    {
        private AppDbContext _db;

        public KategorijaController(AppDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Kategorija> objKategorijaList = _db.Kategorije.ToList();

            return View(objKategorijaList);
        }



        //CREATE
        //GET
        public IActionResult Create()
        {
            Kategorija obj = new Kategorija();
            return View(obj);
        }


        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Kategorija obj)
        {
            if (obj.naziv == obj.vrstniRed.ToString())
            {
                ModelState.AddModelError("CustomError", "Splosna napaka: Naziv ne sme biti enak vrstnemu redu!");

                ModelState.AddModelError("naziv", "Naziv ne sme biti enak vrstnemu redu!");

            }

            if (obj.naziv.Length <= 3)
            {
                ModelState.AddModelError("CustomError", "Naziv mora biti dalši od 3 znakov!");
                TempData["error"] = "Zapis ni bil dodan!";

            }

            //Server Side Validation
            //preverimo veljavnost (če ni veljaven, vrnemo podatke nazaj)
            if (ModelState.IsValid)
            {
                _db.Kategorije.Add(obj);
                _db.SaveChanges();
                //TempData
                TempData["success"] = "Kategorija uspešno ustvarjena!";

                return RedirectToAction("Index");
            }
            return View(obj);
        }





        //EDIT
        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.Kategorije.Find(id);
            //primer 2
            // var obj = _db.Kategorije.FirstOrDefault(a => a.Id == id);
            //var obj2 = _db.Kategorije.SingleOrDefault(a => a.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }


        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Kategorija obj)
        {
            if (obj.naziv == obj.vrstniRed.ToString())
            {
                ModelState.AddModelError("CustomError", "Splosna napaka: Naziv ne sme biti enak vrstnemu redu!");

                ModelState.AddModelError("naziv", "Naziv ne sme biti enak vrstnemu redu!");

            }

            //Server Side Validation
            //preverimo veljavnost (če ni veljaven, vrnemo podatke nazaj)
            if (ModelState.IsValid)
            {
                //sprememba iz Add v Update
                _db.Kategorije.Update(obj);
                _db.SaveChanges();

                TempData["success"] = "Kategorija uspešno posodobljena!";

                return RedirectToAction("Index");
            }
            return View(obj);
        }




        //EDIT
        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.Kategorije.Find(id);
            //primer 2
            // var obj = _db.Kategorije.FirstOrDefault(a => a.Id == id);
            //var obj2 = _db.Kategorije.SingleOrDefault(a => a.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }


        //POST
        //[HttpPost,ActionName("Delete")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {

            var obj = _db.Kategorije.Find(id);

            if (obj == null)
            {
                return NotFound();
            }


            //sprememba iz Update v Remove
            _db.Kategorije.Remove(obj);
            _db.SaveChanges();

            TempData["success"] = "Kategorija uspešno odstranjena!";

            return RedirectToAction("Index");

        }
    }
}

MVC_Vaje202122_Priprava/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVC_Vaje202122_Priprava/Views/Kategorija/Create.cshtml
@model MVC_Vaje202122_Priprava.Models.Kategorija

@{
    ViewData["Title"] = "UstvariZapis";
}

<h1>Ustvari zapis</h1>

<h4>Kategorija</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>
            @* <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            *@

            <div class="form-group">
                <label asp-for="naziv" class="control-label"></label>
                <input asp-for="naziv" class="form-control" />
                <span asp-validation-for="naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="vrstniRed" class="control-label"></label>
                <input asp-for="vrstniRed" class="form-control" />
                <span asp-validation-for="vrstniRed" class="text-danger"></span>
            </div>
            @*      <div class="form-group">
                    <label asp-for="ustvarjeno" class="control-label"></label>
                    <input asp-for="ustvarjeno" class="form-control" />
                    <span asp-validation-for="ustvarjeno" class="text-danger"></span>
                </div> *@
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />

            <a asp-action="Index" class="btn btn-secondary" style="width:200px">Nazaj na seznam</a>
        </div>
        </form>
    </div>
</div>
 

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

MVC_Vaje202122_Priprava/Views/Kategorija/Delete.cshtml
@model MVC_Vaje202122_Priprava.Models.Kategorija

@{
    ViewData["Title"] = "DeleteZapis";
}

<h1>Izbriši zapis</h1>

<h4>Kategorija</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="DeletePost">
            <input asp-for="Id" hidden />
            <div asp-validation-summary="All" class="text-danger"></div>
            @* <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            *@

            <div class="form-group">
                <label asp-for="naziv" class="control-label"></label>
                <input asp-for="naziv" disabled class="form-control" />
                
            </div>
            <div class="form-group">
                <label asp-for="vrstniRed" class="control-label"></label>
                <input asp-for="vrstniRed" disabled class="form-control" />
                
            </div>
            @*      <div class="form-group">
                    <label asp-for="ustvarjeno" class="control-label"></label>
                    <input asp-for="ustvarjeno" class="form-control" />
                    <span asp-validation-for="ustvarjeno" class="text-danger"></span>
                </div> *@
        <div class="form-group">
            <input type="submit" value="Izbriši" class="btn btn-danger" style="width:200px" />
            
            <a asp-action="Index" class="btn btn-secondary" style="width:200px">Nazaj na seznam</a>
        </div>
        </form>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

MVC_Vaje202122_Priprava/Views/Kategorija/Edit.cshtml
@model MVC_Vaje202122_Priprava.Models.Kategorija

@{
    ViewData["Title"] = "EditZapis";
}

<h1>Ustvari zapis</h1>

<h4>Kategorija</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="All" class="text-danger"></div>
            @* <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            *@

            <div class="form-group">
                <label asp-for="naziv" class="control-label"></label>
                <input asp-for="naziv" class="form-control" />
                <span asp-validation-for="naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="vrstniRed" class="control-label"></label>
                <input asp-for="vrstniRed" class="form-control" />
                <span asp-validation-for="vrstniRed" class="text-danger"></span>
            </div>
            @*      <div class="form-group">
                    <label asp-for="ustvarjeno" class="control-label"></label>
                    <input asp-for="ustvarjeno" class="form-control" />
                    <span asp-validation-for="ustvarjeno" class="text-danger"></span>
                </div> *@
        <div class="form-group">
            <input type="submit" value="Popravi" class="btn btn-primary" />

            <a asp-action="Index" class="btn btn-secondary" style="width:200px">Nazaj na seznam</a>
        </div>
        </form>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

MVC_Vaje202122_Priprava/Views/Kategorija/Index.cshtml
@model IEnumerable<Kategorija>

@{
    ViewData["Title"] = "Index";
}

<h1>Index Category</h1>


@*<partial name="_Opozorilo" />*@
@*UPORABA TEMP DATA
    @if (TempData["success"] != null)
    {
        <h2>@TempData["success"]</h2>
    }   *@

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Seznam kategorij</h2>
        </div>
        <div class="col-6">
            <a asp-controller="Kategorija" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i>   Ustvari kategorijo
            </a>
        </div>
    </div>
</div>
<br />
<br />

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Naziv
            </th>
            <th>
                Vrstni red
            </th>
            <th>
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td>
                    @obj.naziv
                </td>
                <td>
                    @obj.vrstniRed
                </td>

                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Kategorija" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary" style="width:75px"><i class="bi bi-pen-fill"></i> Popravi</a>
                        <a asp-controller="Kategorija" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger" style="width:75px"><i class="bi bi-trash"></i> Izbriši</a>

                    </div>

                </td>
            </tr>
        }
    </tbody>
</table>

MVC_Vaje202122_Priprava/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Vaje202122_Priprava</title>
    <link rel="stylesheet" href="~/css/BootStrapTheme.css" />
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href=" //cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_Vaje202122_Priprava</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kategorija" asp-action="Index">Kategorije</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Opozorilo"/>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVC_Vaje202122_Priprava - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVC_Vaje202122_Priprava/Views/Shared/_Opozorilo.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr["success"]('@TempData["success"]');

    </script>
    /*<h2>@TempData["success"]</h2>*/
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr["error"]('@TempData["error"]');

    </script>
   
}